
general {
    color_degraded = "#cb4b16"
    output_format = "i3bar"
    interval = "10"
    #color_bad = "#dc322f"
	colors = "false"
    #color_good = "#859900"
    color_separator = "#586e75"
	separator = " "
}

battery 0 {
    threshold_type = "time"
    integer_battery_capacity = "true"
    low_threshold = "15"
    format = " BATT: %percentage "
}



volume master {
    device = "default"
    mixer_idx = "0"
    mixer = "Master"
    format = " VOL: %volume "
}

disk / {
    format = " DISK: %avail/%total "
}



time {
    format = " %d/%m/%y  %H:%M:%S  "
}


wireless wlo1 {
    format_up = " NET: %essid "
    format_down = " NET: down "
           }


#order += "disk /"
order += "battery 0"
order += "volume master"
order += "wireless wlo1"
order += "time"

